// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  primaryBtn: string;
  root: string;
  smallBtn: string;
  w100: string;
}
export const cssExports: CssExports;
export default cssExports;
