// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  burger: string;
  header: string;
  headerCont: string;
  logo: string;
}
export const cssExports: CssExports;
export default cssExports;
