// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  footer: string;
  footerCont: string;
  footerLink: string;
  footerMake: string;
}
export const cssExports: CssExports;
export default cssExports;
