// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  pokedexPage: string;
  pokedexTitle: string;
  pokemonsWrap: string;
  search: string;
}
export const cssExports: CssExports;
export default cssExports;
