// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button404: string;
  content404: string;
  heading404: string;
  heading404White: string;
  image404: string;
  rootNotFound: string;
  text404: string;
}
export const cssExports: CssExports;
export default cssExports;
